#!/usr/bin/env bash

alias ls='ls     --color=auto'
alias la='ls -l  --color=auto'
alias ll='ls -la --color=auto'
alias gdb='gdb -q'

set  -o vi
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert  'Control-l: clear-screen'

alias cld='wl-paste >'
alias cldi='wl-paste > input'
alias lnd='curl "$( wl-paste )" -O'
alias lndo='curl "$( wl-paste )" -o'

export EDITOR=nvim
export PATH="$HOME/.local/bin:$PATH"

source "$HOME/.local/bin/git-prompt.sh"
export GIT_PS1_SHOWDIRTYSTATE=1
export PS1='\[\e[0;32m\]\w\[\e[m\]$(__git_ps1 " (%s)")\$ '

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - bash)"

