#!/usr/bin/env bash

alias ls='ls     --color=auto'
alias la='ls -l  --color=auto'
alias ll='ls -la --color=auto'

set  -o vi
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert  'Control-l: clear-screen'

export EDITOR=nvim
export PATH="$HOME/.local/bin:$PATH"

source "$HOME/.local/bin/git-prompt.sh"
export GIT_PS1_SHOWDIRTYSTATE=1
export PS1='\e[0;32m\w\e[m$(__git_ps1 " (%s)")\$ '

