#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

_info() {
    printf "%s[info]%s  %s\n" "$( tput setaf 4 )" "$( tput sgr0 )" "$1"
}

_error() {
    printf "%s[error]%s %s\n" "$( tput setaf 1 )" "$( tput sgr0 )" "$1"
}

if [[ ! -f 'map.tsv' ]]; then
    _error 'File map.tsv not found'
    exit 1
fi

while read -r config dest; do
    target="$PWD/config/$config" 
    if [[ ! -e "$target" ]]; then
        _error "$( printf 'Config "%s" not found' "$config" )"
        continue
    fi

    link="$HOME/$dest"
    if [[ -L "$link" ]]; then
        _info "$( printf 'Symlink to "%s" already exists' "$config" )"
        continue
    fi

    if [[ -e "$link" ]]; then
        _error "$( printf 'Symlink path "%s" is already taken by a file' "$link" )"
        continue
    fi

    _info "$( printf 'Creating symlink "%s" to "%s"' "$dest" "$config" )"
    ln -s "$target" "$link"
done < map.tsv
