#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

_info() {
    printf "%s[info]%s  %s\n" "$( tput setaf 4 )" "$( tput sgr0 )" "$1"
}

_error() {
    printf "%s[error]%s %s\n" "$( tput setaf 1 )" "$( tput sgr0 )" "$1"
}

_die() {
    _error "$@"
    exit 1
}

_ensure_dir() {
    dir="$1"

    if [[ -z "$dir" ]]; then
        _die 'Variable "dir" is empty string'
    fi

    if [[ ! -e "$dir" ]]; then
        _info "$( printf 'Creating "%s" directory' "$dir" )"
        mkdir -p "$dir" 
    elif [[ -e "$dir" && ! -d "$dir" ]]; then
        _die "$( printf '"%s" exists but is not a directory' "$dir" )"
    else
        _info "$( printf '"%s" already exists' "$dir" )"
    fi

    unset dir
}

if [[ ! -f 'map.tsv' ]]; then
    _die 'File map.tsv not found'
fi

_ensure_dir "$HOME/.config/custom"
_ensure_dir "$HOME/.local/bin"

while read -r config dest; do
    target="$PWD/config/$config" 
    if [[ ! -e "$target" ]]; then
        _error "$( printf 'Config "%s" not found' "$config" )"
        continue
    fi

    link="$HOME/$dest"
    if [[ -L "$link" ]]; then
        _info "$( printf 'Symlink to "%s" already exists' "$config" )"
        continue
    fi

    if [[ -e "$link" ]]; then
        _error "$( printf 'Symlink path "%s" is already taken by a file' "$link" )"
        continue
    fi

    _info "$( printf 'Creating symlink "%s" to "%s"' "$dest" "$config" )"
    ln -s "$target" "$link"
done < map.tsv
unset config dest target link

_info 'Install successful'
