#!/usr/bin/env bash

projects="$HOME/projects/"
if [[ ! -d "$projects" ]]; then
    echo 'projects not present in $HOME dir' 
    exit 1
fi

name="$( ls "$projects" | fzf-tmux )"
path="$projects/$name"

if ! tmux has-session -t "$name" 2> /dev/null; then
    tmux new -s "$name" -n 'editor' -c "$path" -d
    tmux neww -t "$name" -n 'shell' -d
    tmux send -t "$name" 'nvim' 'C-m'
fi

if [[ -z "$TMUX" ]]; then
    tmux attach -t "$name"
else
    tmux switch-client -t "$name"
fi
