#!/usr/bin/env bash

dirs=( "$HOME" "$HOME/projects/" "$HOME/.config/" )
for dir in "${dirs[@]}"; do
    if [[ ! -d "$dir" ]]; then
        echo "$dir doesn't exist"
        exit 1
    fi
done

path="$( find ${dirs[@]} -maxdepth 1 -type d -not -name ".*" | fzf-tmux )"
if [[ -z "$path" ]]; then
    exit 0
fi
name="$( basename "$path" )"

if ! tmux has-session -t "$name" 2>/dev/null; then
    tmux new -s "$name" -n 'editor' -c "$path" -d
    tmux neww -t "$name" -n 'shell' -c "$path" -d
    tmux neww -t "$name" -n 'debug' -c "$path" -d
    tmux send -t "$name" 'nvim' 'C-m'
fi

if [[ -z "$TMUX" ]]; then
    tmux attach -t "$name"
else
    tmux switch-client -t "$name"
fi
